### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by TacoTheDank**
files changed are separated by their location (by commit)

some readme changes
gradles to 28
java 1.8 compatibility
perhaps pulled latest libraries from https://android.googlesource.com/platform/external/sonivox/+/master/arm-wt-22k/

### CODE REVIEW

**Comment by billthefarmer** [comment]
Thank you. Because the changes you have made to mididriver/library/jni have broken it I will merge this to a branch and fix it before merging to master. There are various bits in the Sonivox sources that have to be commented out because they reference include files not distributed in the NDK. Because it's normally built with the android build system. Also the ARM assembler sources won't compile with the latest NDK because it doesn't have the GCC assembler any more, so the build script doesn't include them.

**Comment by billthefarmer** [comment]
I added some dummy include files rather than editing the sources again.

**Comment by TacoTheDank** [comment]
alright, thank you :)

**Comment by rodneyryan** [comment]
Say, what happened here...?

**Comment by TacoTheDank** [comment]
a merge

**Pull request merged**
